// @generated by schema-rust from an authority-verified bootstrap Interface

pub struct z2Vf6b {
    pub field_0: z2Vf1e,
    pub field_1: z2Vezw,
    pub field_2: z2VRQy,
}
pub enum z2VcWY {z2VLm7 , z2VV66 ,} 
pub struct z2Vezw {
    pub field_0: z2VNuw,
    pub field_1: signal_standard::schema::lib::z2VWWD,
    pub field_2: z2VbaN,
}
pub enum z2Vc6q {z2Vbzp , z2VRy9 , z2VS2U , z2VPvY , z2VMuY , z2VSJs ,} 
pub struct z2VbYc {
    pub field_0: z2Vd7N,
}
pub enum z2VRQy {z2VTjW , z2Vdry , z2VXwE ,} 
pub struct z2VNuw(std::string::String);
impl z2VNuw {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2Vf1e {
    pub field_0: z2Vc6q,
    pub field_1: signal_standard::schema::lib::z2VduW,
}
pub enum z2VLdm {z2VNXr , z2VRYE , z2VVgB ,} 
pub enum z2VXjF {z2VXSA ( z2Vf6b ,) ,} 
pub struct z2VSVQ {
    pub field_0: z2VLdm,
}
pub enum z2VV4Q {z2VbZm ( z2VUw2 ,) , z2VcvR ( z2VbYc ,) , z2VNX3 ( z2VSVQ ,) ,} 
pub struct z2VUw2 {
    pub field_0: z2VZgH,
    pub field_1: z2VcWY,
}
pub enum z2VZgH {z2VT2e ,} 
pub struct z2Vd7N(u64);
impl z2Vd7N {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2VbaN(std::string::String);
impl z2VbaN {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
